- name: Printing high value
  hosts: local
  connection: local
  vars_prompt:
    - name: VALUE
      prompt: enter a value
  tasks: 
  - name: print greater than value
    ansible.builtin.debug:
      msg: "value {{ VALUE }} is greater than 10"
    when: VALUE > 10

  - name: print less than or equal value
    ansible.builtin.debug:
      msg: "value {{ VALUE }} is less than 10 or equal to 10"
    when: VALUE <= 10