- name: create ec2 instance and route 53
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-05570ac26e3822fff
    vpc_id: vpc-0bad1db2654f40862
    subnet_id: subnet-04965604c2a51a1a1
    instance_type: t2.micro
    region: us-east-1
    zone: devopsaws.fun
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install dependices
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - botocore
    - boto3
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print ec2 info
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results}}"

   - name: create private ip r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item}}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"

