- name: install and run nginx
  hosts: all
  become: yes
  serial: 10
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
  #     enabled: yes
  # - name: Get facts
  #   debug:
  #     msg: "{{ ansible_facts.services['nginx'].status }}"