- name: packeage
  hosts: web
  become: yes
  tasks: 
  - name: install httpd package
    ansible.builtin.package:
      name: httpd
      state: latest
  - name: service starting
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes