- name: shell and command module
  hosts: local
  connection: local
  tasks:
  - name: testing shell command
    ansible.builtin.shell: ls -ltr /home/ec2-user/ansible
    register: result
  - name: printing
    ansible.builtin.debug:
      msg: "{{ result }}"

  - name: testing shell command
    ansible.builtin.command: ls -ltr /home/ec2-user/ansible
