- name: shell and command module
  hosts: local
  connection: local
  tasks:
  - name: testing shell command
    ansible.builtin.shell: ls -ltr /home/ec2-user/ansible
    register: result
    ansible.builtin.debug:
      msg: "{{ result }}"