- name: taking values from user end
  hosts: local
  connection: local
  vars_prompt:
  - name: NAME
    prompt: Enter Your Name
    private: false
  - name: PASSWORD
    prompt: Enter Your password
    private: false
  tasks:
  - name: printing the value
    ansible.builtin.debug:
      msg: "your name is {{ NAME }} and password is {{ PASSWORD }}"
  