- name: varaible
  hosts: local
  connection: local
  vars:
    VAR1: "Hello From First"
    TASK: Task
  tasks:
  - name: print first line 
    ansible.builtin.debug:
      msg: "{{ VAR1 }} {{ TASK }}"

  - name: print second line
    vars_prompt:
    - name: VAR2
      prompt: enter username
    - name: TASK1
      prompt: enter password
    ansible.builtin.debug:
      msg: "{{ VAR2 }} {{ TASK1 }}"