- name: varaible
  hosts: local
  connection: local
  vars_prompt:
    - name: VAR2
      prompt: enter username
    - name: TASK1
      prompt: enter password
  tasks:
  - name: printing data from prompt
    ansible.builtin.debug:
      msg: "{{ VAR2 }} {{ TASK1 }}"