- name: Entering values from args
  hosts: local
  connection: local
  tasks:
  - name: taking values from command line
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} and password is {{ PWD }}"