- name: print name
  hosts: local
  connection: local
  vars_prompt:
    - name: NAME
    prompt: Enter your name
  tasks:
  - name: print name
    ansible.builtin.debug:
      msg: "your name is {{ NAME }}"
    when: NAME == "prakash"