- name: print name
  hosts: local
  connection: local
  vars_prompt:
    - name: NAME
      prompt: Enter your name
  tasks:
  - name: print name
    ansible.builtin.debug:
      msg: "your name is {{ NAME }}"
    when: NAME == "prakash"

  - name: print error msg if user entered wrong username
    ansible.builtin.debug:
      msg: "you entered wrong username {{ NAME }}"
    when: NAME != "prakash"